# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal8535-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter a14x m14x,$(TARGET_DEVICE)),)

endif
